server:
  port: 9527

spring:
  application:
    name: mycloud-zuul-gateway

zuul:
  prefix: /gcj  # 统一的公共前缀
  ignored-services: "*" # 禁用所有服务 "*" ，单个禁用直接输入服务名即可
  routes:  # 路由映射
    mydept.serviceId: mycloud-dept
    mydept.path: /mydept/**

eureka:
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false  #false表示不需要取检索服务
